### Homework solutions


## Needlman-Wunsch



Sequence 1: AGTACGCA
Sequence 2: --TATGC-
Alignment Score: 1


## Affine gap algorithm

302
PTIMWAYSKPVSNGIM------------FLILLTWCRCYIRPSNFHMRTQNWTFKVNQLLPLDKYSCMWGIQGMYASTWLSHGCVRVWQYPVM
PFGKWTHLI-VSNGIYNSQWTTHHNFQESLELLTWCRCYIRPS---MRTQNWTFKVNQLLPLDKYSCMWKIQGMYAST-LSHGCVRVWQYPVM


## Number of alignments

### Four Russian Algorithm

In [1]:
import itertools
import numpy as np

# Define basic constants
t = 4  # block size
alphabet = ['A', 'G']
substitution_matrix = {
    ('A', 'A'): 1,
    ('G', 'G'): 1,
    ('A', 'G'): -1,
    ('G', 'A'): -1,
}
gap_penalty = -1

In [2]:
# Generate all possible 5-letter words from A/G
words = [''.join(p) for p in itertools.product(alphabet, repeat=t)]

In [3]:
print(words)

['AAAA', 'AAAG', 'AAGA', 'AAGG', 'AGAA', 'AGAG', 'AGGA', 'AGGG', 'GAAA', 'GAAG', 'GAGA', 'GAGG', 'GGAA', 'GGAG', 'GGGA', 'GGGG']


In [20]:
def compute_block(top_seq, left_seq, top_deltas, left_deltas):
    """
    Returns deltas of the last row and column after computing a t×t block
    given top and left sequence segments and their deltas.
    """
    t = len(top_seq)
    dp = np.zeros((t + 1, t + 1), dtype=int)

    # Reconstruct top_scores and left_scores from deltas

    dp[0, 1:] = top_deltas
    dp[1:, 0] = left_deltas

    for i in range(1, t + 1):
        for j in range(1, t + 1):
            match = dp[i-1][j-1] + substitution_matrix[(left_seq[i-1], top_seq[j-1])]
            delete = dp[i-1][j] + gap_penalty
            insert = dp[i][j-1] + gap_penalty
            dp[i][j] = max(match, delete, insert)

    block = dp[1:, 1:]
   

    # Compute deltas for last row and column
    last_row_deltas = [block[-1][0] - left_scores[-1]]
    for j in range(1, t):
        last_row_deltas.append(block[-1][j] - block[-1][j - 1])

    last_col_deltas = [block[0][-1] - top_scores[-1]]
    for i in range(1, t):
        last_col_deltas.append(block[i][-1] - block[i - 1][-1])
    print(last_col_deltas, last_col_deltas)
    return last_row_deltas, last_col_deltas



In [ ]:
# Precompute all block results
precomputed_blocks = {}

# With gap_penalty = -1, limit deltas to -1 or 0 (no insertion) or 1 (extension from match)
possible_deltas = [-1, 0, 1]

for top_seq in words:
    print("here")

    for left_seq in words:
        for top_deltas in itertools.product(possible_deltas, repeat=t):

            for left_deltas in itertools.product(possible_deltas, repeat=t):
                key = (top_seq, left_seq, tuple(top_deltas), tuple(left_deltas))
                precomputed_blocks[key] = compute_block(top_seq, left_seq, top_deltas, left_deltas)
#

print(f"Precomputed {len(precomputed_blocks)} blocks.")

In [8]:
import random

# Step 1: Generate random A/G sequences of length 100
seq1 = ''.join(random.choices(alphabet, k=100))
seq2 = ''.join(random.choices(alphabet, k=100))

# Step 2: Initialize full DP matrix
dp_full = np.zeros((len(seq1) + 1, len(seq2) + 1), dtype=int)

# Initialize first row and column with gap penalties
for i in range(1, len(seq1) + 1):
    dp_full[i][0] = dp_full[i - 1][0] + gap_penalty
for j in range(1, len(seq2) + 1):
    dp_full[0][j] = dp_full[0][j - 1] + gap_penalty

# Step 3: Fill the matrix using 4x4 blocks and precomputed results
for i_block in range(0, len(seq1), t):
    for j_block in range(0, len(seq2), t):
        # Get top sequence (along columns) and left sequence (along rows) for the block
        top_seq = seq2[j_block:j_block + t]
        left_seq = seq1[i_block:i_block + t]

        # Get boundary scores
        top_scores = dp_full[i_block][j_block + 1:j_block + t + 1]
        left_scores = dp_full[i_block + 1:i_block + t + 1, j_block]
        # Compute deltas (differences between consecutive values)
        top_deltas = np.diff(np.insert(top_scores, 0, 0))
        left_deltas = np.diff(np.insert(left_scores, 0, 0))

        key = (top_seq, left_seq, tuple(top_deltas), tuple(left_deltas))
        block = precomputed_blocks.get(key)
        print(block)
        if block is None:
            # Fallback to direct computation (shouldn’t happen if preprocessing is complete)
            block = compute_block(top_seq, left_seq, top_scores, left_scores)

        # Insert the block into the DP matrix
        for i in range(t):
            for j in range(t):
                if i_block + i + 1 <= len(seq1) and j_block + j + 1 <= len(seq2):
                    dp_full[i_block + i + 1][j_block + j + 1] = block[i][j]

print("DP matrix built using 5x5 Four Russians blocks!")

None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
[[0 0 1 0]
 [1 3 2 1]
 [0 2 3 4]
 [1 2 4 4]]
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
[[ 0 -1  2  1]
 [ 2  2  2  2]
 [ 1  2  3  4]
 [ 0  2  3  3]]
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None

In [17]:
print(dp_full)

[[   0   -1   -2 ...  -98  -99 -100]
 [  -1   -1    0 ...   -2   -3   -4]
 [  -2    0   -1 ...   -2   -3   -2]
 ...
 [ -98   -2   -2 ...   43   43   45]
 [ -99   -3   -1 ...   42   44   44]
 [-100   -4   -2 ...   41   43   43]]


### Experimenting with BLAST

## Random Sequences and BLAST.
Sequence alignments can be performed online using the programs and data provided by the National Center for Biotechnology Information (NCBI).


## Task 1

Generate a random amino acid sequence and run it against a database of non-redundant sequences employing BLAST (http://www.ncbi.nlm.nih.gov/BLAST/); use the standard protein-protein BLAST [blastp]. Create a single fasta that contains several amino acid sequences of length 10, 50, 100, 1500 aminoacids. Did you find any “false homologous” in the database?

## Task 2

Generate a random amino acid sequences with amino acid frequencies from the table below and with PERIODICITY of hydrophobic and non-hydrophobic residues. Run these sequences using BLAST. Interpret your results.

In [21]:
import pandas as pd

# Amino acid information
amino_acids = {
    'CYS': {'hydrophobic': True, 'value': 1.660},
    'MET': {'hydrophobic': True, 'value': 2.370},
    'PHE': {'hydrophobic': True, 'value': 4.100},
    'ILE': {'hydrophobic': True, 'value': 5.810},
    'LEU': {'hydrophobic': True, 'value': 9.430},
    'VAL': {'hydrophobic': True, 'value': 6.580},
    'TRP': {'hydrophobic': True, 'value': 1.240},
    'TYR': {'hydrophobic': True, 'value': 3.190},
    'ALA': {'hydrophobic': True, 'value': 7.580},
    'GLY': {'hydrophobic': True, 'value': 6.840},
    'THR': {'hydrophobic': False, 'value': 5.670},
    'SER': {'hydrophobic': False, 'value': 7.130},
    'GLN': {'hydrophobic': False, 'value': 3.970},
    'ASN': {'hydrophobic': False, 'value': 4.440},
    'GLU': {'hydrophobic': False, 'value': 6.360},
    'ASP': {'hydrophobic': False, 'value': 5.270},
    'HIS': {'hydrophobic': False, 'value': 2.240},
    'ARG': {'hydrophobic': False, 'value': 5.160},
    'LYS': {'hydrophobic': False, 'value': 5.940},
    'PRO': {'hydrophobic': False, 'value': 4.920}
}

# Create DataFrame
df = pd.DataFrame.from_dict(amino_acids, orient='index')
df.index.name = 'Amino Acid'


# Add 'One_Letter' column
one_letter_mapping = {
    'CYS': 'C', 'MET': 'M', 'PHE': 'F', 'ILE': 'I', 'LEU': 'L',
    'VAL': 'V', 'TRP': 'W', 'TYR': 'Y', 'ALA': 'A', 'GLY': 'G',
    'THR': 'T', 'SER': 'S', 'GLN': 'Q', 'ASN': 'N', 'GLU': 'E',
    'ASP': 'D', 'HIS': 'H', 'ARG': 'R', 'LYS': 'K', 'PRO': 'P'
}

df['One_Letter'] = df.index.map(one_letter_mapping)


# Display the DataFrame
print(df)

            hydrophobic  value One_Letter
Amino Acid                               
CYS                True   1.66          C
MET                True   2.37          M
PHE                True   4.10          F
ILE                True   5.81          I
LEU                True   9.43          L
VAL                True   6.58          V
TRP                True   1.24          W
TYR                True   3.19          Y
ALA                True   7.58          A
GLY                True   6.84          G
THR               False   5.67          T
SER               False   7.13          S
GLN               False   3.97          Q
ASN               False   4.44          N
GLU               False   6.36          E
ASP               False   5.27          D
HIS               False   2.24          H
ARG               False   5.16          R
LYS               False   5.94          K
PRO               False   4.92          P


In [20]:
df

hydrophobic  value
Amino Acid                    
CYS                True   1.66
MET                True   2.37
PHE                True   4.10
ILE                True   5.81
LEU                True   9.43
VAL                True   6.58
TRP                True   1.24
TYR                True   3.19
ALA                True   7.58
GLY                True   6.84
THR               False   5.67
SER               False   7.13
GLN               False   3.97
ASN               False   4.44
GLU               False   6.36
ASP               False   5.27
HIS               False   2.24
ARG               False   5.16
LYS               False   5.94
PRO               False   4.92

Random Sequence: QRKEICYIAKNPTKKENKKRIMFWLIYIFGVAIQSKHPQDDNPTFAMGGC


### Task 3 
Take an amino acid sequence (a protein of your choice, or one of proteins suggested below) and introduce X% of random mutations. Run mutated proteins against the database
using BLAST or PSI-BLAST (same web page). Try different frequency of mutations (X = 0, · · · 100%). What level of mutations is tolerated by BLAST? by PSI-BLAST? Interpret
your results.

Myoglobin: "MAKRRGSVPGRVREYWLPSPCWKCHMLHQGKWWGRRSQGMGGAEGFMEHGSTTLQRKPGASSELGILQVRDLSWLVQPQAQTCCGSFVPLSAGLRASAK"
Histon H2B: "MTDKITKKKRNETYSIYIYKVLRQVHPKIGVSSKAMNIMNSFVNDLFERLVSESYNLSNSSRSKTLTAREIQTSVRLVIPGELAKHSVSEGTKAVAKYRSSI"
SH3 Domain: "MDETGKELVLALYDYQEKSPREVTMKKGDILTLLNSTNKDWWKVEVNDRQGYVPAAYVKKLD"

### Task 4

Introduce X% of mutations such that a hydrophobic amino acid is substituted by a random hydrophobic one and vice versa. Run using BLAST. Did the threshold level for X change?